"""adds Ingredient and BreakfastIngredient models

Revision ID: 202ef4c2e8e3
Revises: bd60910981f7
Create Date: 2022-11-12 13:42:00.466680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202ef4c2e8e3'
down_revision = 'bd60910981f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient')
    # ### end Alembic commands ###
